module.exports = {
  testEnvironment: 'jsdom',
  setupFiles: ['<rootDir>/tests/setup-node-web-globals.js'],
  verbose: true,
  testMatch: [
    '**/tests/unit/**/*.test.js',
    '**/tests/integration/**/*.test.js',
    '**/tests/contract/**/*.test.js',
    '**/tests/structure/**/*.test.js',
    '**/tests/a11y/**/*.test.js',
    '**/tests/e2e/**/*.test.js',
  ],
  testPathIgnorePatterns: [
    '<rootDir>/\\.claude/',
  ],
  modulePathIgnorePatterns: [
    '<rootDir>/\\.claude/',
    '<rootDir>/docs/legacy/backend-placeholder/',
    '<rootDir>/dist/',
  ],
  collectCoverage: true,
  coverageDirectory: 'output/coverage',
  coverageReporters: ['text', 'text-summary'],
  collectCoverageFrom: [
    'assets/js/boot/kc-constants.js',
    'assets/js/utils/kc-utils.js',
    'assets/js/api/kc-api.client.js',
    'assets/js/features/kc-filters.js',
    'assets/js/features/kc-ranking.js',
    'assets/js/shared/account-profile.shared.js',
    'assets/js/shared/help.shared.js',
    'assets/js/shared/home-categories.shared.js',
    'assets/js/shared/kc-comments.shared.js',
    'assets/js/shared/kc-search.shared.js',
    'assets/js/shared/ods.shared.js',
    'assets/js/shared/search-analytics.shared.js',
    'assets/js/adapters/local/local.notifications.adapter.js',
    'assets/js/adapters/local/local.ratings.adapter.js',
    'assets/js/adapters/local/local.saved.adapter.js',
    'assets/js/adapters/local/local.posts-read.adapter.js',
    'assets/js/adapters/local/local.posts-write.adapter.js',
    'assets/js/adapters/local/local.profile.adapter.js',
    'assets/js/adapters/local/local.help.adapter.js',
    'assets/js/adapters/local/local.adapter.js',
  ],
};
